// #409 (S7): the exec-lever environment-key rule for git and ripgrep (plus the helpers they spawn).
//
// DEFAULT-DENY, not an inventory: every key under a lever prefix is a lever, with no allowlist of "inert" GIT_*
// variables (an inert-list is a hand-derived claim that rots when git adds a variable). The named set covers keys that
// move or feed a config location or a helper program. Completeness against git's own list is checked by an instrument:
// src/qa/git-rg-lever-seal.test.ts reads docs/qa/git-env-vars-snapshot.txt (generated by `npm run qa:git-env-snapshot`
// from git's ENVIRONMENT documentation) and fails on any GIT_* token this rule misses.
//
// Keys are matched case-insensitively (Windows environment keys are case-insensitive).
// Used by: the settings-env scan below, and src/qa/git-rg-lever-preflight.ts.
export const LEVER_PREFIXES: readonly string[] = ["GIT_", "RIPGREP_"];

export const LEVER_NAMED: readonly string[] = [
  "PAGER", // git's pager when core.pager is unset; also read by man, less-aware tools
  "EDITOR",
  "VISUAL",
  "LESS",
  "LESSOPEN", // pager preprocessor: runs a command on each file viewed
  "LESSSECURE",
  "SSH_ASKPASS",
  "SSH_AUTH_SOCK",
  "HOME", // relocates ~/.gitconfig and ~/.config/git
  "USERPROFILE", // the Windows equivalent
  "HOMEDRIVE",
  "HOMEPATH",
  "XDG_CONFIG_HOME", // relocates ~/.config/git
  "PROGRAMDATA", // relocates the Windows system gitconfig (%PROGRAMDATA%\Git\config)
  "KUBECONFIG", // read side of the kubectl exec-plugin lever (Issue #409 kubectl comment, F9)
];

/** Lever keys that a normal developer environment sets on purpose. A settings env block carrying one is still a
 * finding; the process-env check of the preflight does not report these (they are always set, so a report would be
 * noise and hide real findings). The effect of a relocated HOME is covered by reading the files it points at. */
export const AMBIENT_COMMON: readonly string[] = ["PAGER", "EDITOR", "VISUAL", "LESS", "SSH_AUTH_SOCK", "HOME", "USERPROFILE", "HOMEDRIVE", "HOMEPATH", "PROGRAMDATA"];

export function isLeverKey(key: string): boolean {
  const k = key.toUpperCase();
  return LEVER_PREFIXES.some((p) => k.startsWith(p)) || LEVER_NAMED.includes(k);
}

export function isAmbientCommon(key: string): boolean {
  return AMBIENT_COMMON.includes(key.toUpperCase());
}

export interface SettingsEnvHit {
  scope: string;
  key: string;
}

/** Lever keys in the `env` block of one settings file's text. Throws on unparseable JSON (fail closed: a file that
 * cannot be read as settings cannot be shown clean). A missing or non-object `env` is clean. */
export function scanSettingsEnv(scope: string, text: string): SettingsEnvHit[] {
  const parsed = JSON.parse(text) as { env?: unknown };
  const env = parsed.env;
  if (typeof env !== "object" || env === null || Array.isArray(env)) return [];
  return Object.keys(env)
    .filter(isLeverKey)
    .sort()
    .map((key) => ({ scope, key }));
}
