// #409 (S7): generates docs/qa/git-env-vars-snapshot.txt, the vendored list of every GIT_* variable token in git's own
// documentation (its HTML docs directory, found with `git --html-path`). The seal test reads the snapshot so it runs
// where git is not installed. This is a dev-time generator: it runs git once, to find the docs directory; the
// preflight (git-rg-lever-preflight.ts) never does.
//
// Usage: node src/qa/git-env-snapshot.ts [--write] [path/to/git-docs-dir]
//   default: check mode (exit 1 on drift, exit 0 with a note if the git docs are not installed)
//   --write: regenerate the snapshot (exit 1 if the docs are not installed)
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const SNAPSHOT = fileURLToPath(new URL("../../docs/qa/git-env-vars-snapshot.txt", import.meta.url));
const TOKEN = /\bGIT_[A-Z0-9_]+\b/g;
const HEADER = [
  "# GIT_* variable tokens found in git's documentation (git.html, git-config.html, git-var.html and the other pages of the",
  "# docs directory), one per line, sorted. Generated by: node src/qa/git-env-snapshot.ts --write. Do not hand-edit.",
  "# Read by src/qa/git-rg-lever-seal.test.ts: every token must match the lever rule in src/qa/exec-lever-env.ts.",
];

export function tokensIn(texts: readonly string[]): string[] {
  const found = new Set<string>();
  for (const t of texts) for (const m of t.matchAll(TOKEN)) found.add(m[0].replace(/_+$/, ""));
  return [...found].sort();
}

function docsDir(arg: string | undefined): string | undefined {
  if (arg !== undefined) return arg;
  const r = spawnSync("git", ["--html-path"], { encoding: "utf8", windowsHide: true });
  const dir = r.status === 0 ? r.stdout.trim() : "";
  return dir !== "" && existsSync(join(dir, "git.html")) ? dir : undefined;
}

export function main(argv: readonly string[]): number {
  const write = argv.includes("--write");
  const dir = docsDir(argv.find((a) => !a.startsWith("--")));
  if (dir === undefined) {
    console.log("git-env-snapshot: git's HTML docs are not installed here, nothing to compare");
    return write ? 1 : 0;
  }
  const pages = readdirSync(dir).filter((f) => f.endsWith(".html")).map((f) => readFileSync(join(dir, f), "utf8"));
  const want = `${[...HEADER, ...tokensIn(pages)].join("\n")}\n`;
  if (write) {
    writeFileSync(SNAPSHOT, want, "utf8");
    console.log(`git-env-snapshot: wrote ${String(tokensIn(pages).length)} tokens to docs/qa/git-env-vars-snapshot.txt`);
    return 0;
  }
  const have = existsSync(SNAPSHOT) ? readFileSync(SNAPSHOT, "utf8").replaceAll("\r\n", "\n") : "";
  if (have !== want) {
    console.error("git-env-snapshot: DRIFT; run: node src/qa/git-env-snapshot.ts --write");
    return 1;
  }
  console.log(`git-env-snapshot: PASS, snapshot matches git's docs (${String(tokensIn(pages).length)} tokens)`);
  return 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) process.exitCode = main(process.argv.slice(2));
