// Black-box acceptance tests for the S7 kernel-gate classification story (Issue #93, #288
// preconditions, #107), hook layer: `hooks/pretooluse-kernel-gate.mjs` after it consumes the
// loader's resolved rules and posture and classifies `mcp__` tool calls. Written FIRST by
// test-writer, before any production code exists (docs/plans/s7-kernel-gate-classification-
// phase1-2026-09-26.md revision 3, section 7 "H: hook black-box (TW)", section 11).
//
// Every check runs in a registry-pinned copy-tree sandbox (hooks/test-support/gate-sandbox.ts) and
// spawns the copied hook exactly as Claude Code does (node script, JSON on stdin, decision read
// from stdout and the exit code). Read that helper's header for the strict outcome rules:
//   - a DENY is exit 0 plus an explicit deny JSON (a crash or exit 2 is NOT a deny);
//   - an ALLOW is exit 0 with EMPTY stdout and EMPTY stderr (Q-B: the gate emits nothing on allow).
//
// TRACEABILITY. Each test title starts with `AC-H<n>`, the plan's own check id (H1..H13 plus
// H11b, 14 checks). The receipt's "mapped n/n" count is generated by grepping these tags.
//
// NAMES. No committed fixture entry name is typed anywhere in this file (PC-11, G19,
// THOTH-ADR-0001 rule 1): committed entries are read from the fixture at run time; every other
// server name below is a stand-in that is not a committed entry ("docs", "my server", ...).
//
// KNOWN LIMITS, disclosed. (1) The plan's H3/H4 say the deny reason "names the unresolved cause".
// The kernel's POL-05 rule reports an opaque record with the fixed reason "POL-05: mutating
// action's source is opaque" (kernel.ts pol05Rule checks `source` before it reads `unresolved`),
// so the cause text is NOT in the reason as the plan's record shape stands. These tests therefore
// assert the deny came from POL-05 (not from the pre-kernel refusal for an unroutable name) and do
// not assert cause wording; see the report for the plan defect. (2) H13 needs the gate module's
// export name and result shape, which the plan does not define; it derives the export name from
// the hook's own import at run time and mutates the REAL gate result shape-agnostically.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {
  classify,
  createGateSandbox,
  denyReason,
  describeRun,
  firstCommittedEntryName,
  isBlocking,
  isSilentAllow,
  makeDecoyProjectTree,
  readCommittedFixture,
  wasPolicyDenied,
  type GateRun,
  type GateSandbox,
} from "./test-support/gate-sandbox.ts";

// The marker verbs and identity-target grammar are the plan's own encoding (section 4).
const MARKER_READ_ONLY = "tool-class:read-only";
const MARKER_REMOTE_MUTATING = "tool-class:remote-mutating";
const BASH_GET = "kubectl get pod/x --context=c";
const BASH_DELETE = "kubectl delete pods/x --context=c";

type Effect = "allow" | "deny";
interface TestRule {
  id: string;
  effect: Effect;
  verbs?: string[];
  targets?: string[];
  rationale?: string;
}
function policyOf(opts: { defaultOutcome?: Effect; rules?: TestRule[] }): Record<string, unknown> {
  return {
    version: "0.0.0-s7-h-test",
    ...(opts.defaultOutcome === undefined ? {} : { defaultOutcome: opts.defaultOutcome }),
    rules: opts.rules ?? [],
  };
}

function assertSilentAllow(run: GateRun, what: string): void {
  assert.ok(isSilentAllow(run), `${what}: expected an ALLOW that emits nothing (exit 0, empty stdout, empty stderr); got ${describeRun(run)}`);
}
function assertPolicyDenied(run: GateRun, what: string): void {
  assert.ok(wasPolicyDenied(run), `${what}: expected a strict policy DENY (exit 0 plus an explicit deny JSON with a reason; exit 2 or a crash does not count); got ${describeRun(run)}`);
}
/** A deny that the KERNEL produced for an unclassified/unresolved MCP call (POL-05), as opposed to
 * the pre-kernel refusal for an unroutable tool_name. */
function assertKernelUnresolvedDeny(run: GateRun, what: string): void {
  assertPolicyDenied(run, what);
  assert.match(denyReason(run), /POL-05/, `${what}: expected the deny to come from the kernel's POL-05 rule (an unclassified or unresolved MCP call is denied fail-closed), not a generic refusal; got reason=${JSON.stringify(denyReason(run))}`);
}

// --- H1 -----------------------------------------------------------------------------------------

test("AC-H1: an MCP tool of a classified server (the first committed fixture entry, name read from the fixture) is not denied: exit 0, empty stdout, empty stderr", () => {
  const sb = createGateSandbox();
  const name = firstCommittedEntryName();
  assertSilentAllow(sb.mcp(name, "x"), `mcp__${name}__x`);
});

// --- H2 -----------------------------------------------------------------------------------------

test("AC-H2: tool_name Edit is denied (strict helper; complements locked AC-19, which stays unmodified)", () => {
  const sb = createGateSandbox();
  assertPolicyDenied(sb.call("Edit", { file_path: "a.txt", old_string: "a", new_string: "b" }), "tool_name Edit");
});

// --- H3 -----------------------------------------------------------------------------------------

test("AC-H3: an MCP tool of an unclassified server (mcp__nosuchserver__x) is denied (strict), by the kernel's POL-05 rule", () => {
  const sb = createGateSandbox();
  assertKernelUnresolvedDeny(sb.mcp("nosuchserver", "x"), "mcp__nosuchserver__x");
});

// --- H4 -----------------------------------------------------------------------------------------

interface NameCase {
  label: string;
  entries: { name: string; class: string }[];
  server: string;
  tool: string;
  expect: "allow" | "deny";
}

test("AC-H4: server-name mapping is injective-or-unresolved: stand-in entries admitted only when solely [A-Za-z0-9-], exact lookup, ambiguous names denied by POL-05", () => {
  const sb = createGateSandbox();
  const committed = firstCommittedEntryName();
  const ro = "read-only";
  const cases: NameCase[] = [
    // the control: an admitted stand-in resolves
    { label: "stand-in docs is admitted (control)", entries: [{ name: "docs", class: ro }], server: "docs", tool: "x", expect: "allow" },
    // R-D: a tool segment with a triple underscore, or a second double underscore, is ambiguous
    { label: "mcp__docs___x (triple underscore) is unresolved", entries: [{ name: "docs", class: ro }], server: "docs", tool: "_x", expect: "deny" },
    { label: "mcp__docs__evil__x (second double underscore) is unresolved", entries: [{ name: "docs", class: ro }], server: "docs", tool: "evil__x", expect: "deny" },
    // exact lookup only: no prefix and no longest match (kills the prefix-lookup mutant at hook level too)
    { label: "mcp__docs-evil__x is not classified by entry docs", entries: [{ name: "docs", class: ro }], server: "docs-evil", tool: "x", expect: "deny" },
    { label: "mcp__docsevil__x is not classified by entry docs", entries: [{ name: "docs", class: ro }], server: "docsevil", tool: "x", expect: "deny" },
    { label: "mcp__docs2__x is not classified by entry docs", entries: [{ name: "docs", class: ro }], server: "docs2", tool: "x", expect: "deny" },
    { label: "mcp__doc__x (a proper prefix of docs) is not classified", entries: [{ name: "docs", class: ro }], server: "doc", tool: "x", expect: "deny" },
    // the charset admission rule: a rejected entry classifies nothing
    { label: 'stand-in entry "my server" is rejected: mcp__my_server__x denied', entries: [{ name: "my server", class: ro }], server: "my_server", tool: "x", expect: "deny" },
    { label: 'entries "my server" plus my_server: mcp__my_server__x denied', entries: [{ name: "my server", class: ro }, { name: "my_server", class: ro }], server: "my_server", tool: "x", expect: "deny" },
    { label: "stand-in entry my_server alone: mcp__my_server__x denied (underscore names are not admitted)", entries: [{ name: "my_server", class: ro }], server: "my_server", tool: "x", expect: "deny" },
    // the first committed entry: the same name resolves with a plain tool segment (control) and is
    // denied when the tool segment holds a triple underscore
    { label: "the first committed entry with a plain tool segment resolves (control)", entries: [], server: committed, tool: "x", expect: "allow" },
    { label: "the first committed entry with a triple-underscore tool segment is denied", entries: [], server: committed, tool: "a___b", expect: "deny" },
  ];
  for (const c of cases) {
    // an empty `entries` list means: the committed fixture entries, read from the committed file
    sb.setEntries(c.entries.length > 0 ? c.entries : readCommittedFixture().centralLayer.tools);
    const run = sb.mcp(c.server, c.tool);
    const what = `${c.label} (mcp__${c.server}__${c.tool})`;
    if (c.expect === "allow") assertSilentAllow(run, what);
    else assertKernelUnresolvedDeny(run, what);
  }
});

// --- H5 -----------------------------------------------------------------------------------------

test("AC-H5: the loader's resolved posture reaches the kernel: project defaultOutcome deny denies a read-only Bash call; defaultOutcome allow does not", () => {
  const sb = createGateSandbox();
  sb.writeProjectPolicy(policyOf({ defaultOutcome: "deny" }));
  assertPolicyDenied(sb.bash(BASH_GET), `Bash "${BASH_GET}" under project posture deny`);
  sb.writeProjectPolicy(policyOf({ defaultOutcome: "allow" }));
  assertSilentAllow(sb.bash(BASH_GET), `Bash "${BASH_GET}" under project posture allow`);
});

// --- H6 -----------------------------------------------------------------------------------------

test("AC-H6: a corrupt project policy denies Bash and MCP calls (strict); the reason names layer project and kind json-parse-error and never carries the file bytes", () => {
  const sb = createGateSandbox();
  // A bare token where a rule object belongs: V8's JSON.parse message echoes a window of the source
  // around the error, so an implementation that forwards the raw loader message would carry this
  // canary (and the file path the loader prefixes to its message) into the deny reason.
  const canary = "CANARY-ZQX-7431-DO-NOT-ECHO";
  sb.writeProjectPolicy(`{ "version": "v", "rules": [ ${canary} ] }`);
  const calls: [string, GateRun][] = [
    ["Bash", sb.bash(BASH_GET)],
    ["MCP call", sb.mcp(firstCommittedEntryName(), "x")],
  ];
  for (const [label, run] of calls) {
    assertPolicyDenied(run, `${label} with a corrupt project policy`);
    const reason = denyReason(run);
    assert.match(reason, /project/, `${label}: the reason must name the failing layer (project); got ${JSON.stringify(reason)}`);
    assert.match(reason, /json-parse-error/, `${label}: the reason must name the failure kind (json-parse-error); got ${JSON.stringify(reason)}`);
    assert.ok(!reason.includes(canary), `${label}: the reason must NOT contain the policy file's bytes (layer and kind only); got ${JSON.stringify(reason)}`);
    assert.ok(!reason.includes(sb.root), `${label}: the reason must NOT carry the loader's raw message (it prefixes the policy file's path); got ${JSON.stringify(reason)}`);
    assert.ok(!run.stdout.includes(canary), `${label}: stdout must NOT contain the policy file's bytes`);
  }
});

// --- H7 -----------------------------------------------------------------------------------------

test("AC-H7: class is rule data, both directions: a project deny rule on the remote-mutating marker plus the first fixture entry's server denies that server's MCP call; flipping the entry to read-only stops the deny", () => {
  const sb = createGateSandbox();
  const name = firstCommittedEntryName();
  const rationale = "H7-CLASS-RULE-DENY-MARKER";
  sb.writeProjectPolicy(
    policyOf({ rules: [{ id: "h7-deny-remote-mutating-server", effect: "deny", verbs: [MARKER_REMOTE_MUTATING], targets: [`mcp/${name}/`], rationale }] }),
  );
  // direction 1: the committed fixture, UNMODIFIED. If the committed entry were reclassified this
  // answer key is what surfaces it (mutant M2: the first committed entry flipped to read-only).
  const denied = sb.mcp(name, "x");
  assertPolicyDenied(denied, `mcp__${name}__x with the fixture as committed`);
  assert.equal(denyReason(denied), rationale, "the deny must come from the project rule keyed on the marker verb (the rule's own rationale is the reason), not from a generic refusal");
  // direction 2: the sandbox fixture flips this entry to read-only; the same rule no longer matches
  sb.editFixture((fixture) => {
    const entry = fixture.centralLayer.tools.find((t) => t.name === name);
    assert.ok(entry !== undefined, "the sandbox fixture must still list the first committed entry");
    entry.class = "read-only";
  });
  assertSilentAllow(sb.mcp(name, "x"), `mcp__${name}__x after the sandbox fixture flips the entry to read-only`);
});

// --- H8 -----------------------------------------------------------------------------------------

test("AC-H8: fixture entries naming Write, Edit, Task, Bash as read-only have no effect (gate scope is Bash plus mcp__ only): Write, Edit, Task stay denied; Bash delete is treated exactly as with no such entries", () => {
  const planted = createGateSandbox();
  const plainBaseline = createGateSandbox();
  planted.editFixture((fixture) => {
    for (const name of ["Write", "Edit", "Task", "Bash"]) fixture.centralLayer.tools.push({ name, class: "read-only" });
  });
  for (const toolName of ["Write", "Edit", "Task"]) {
    assertPolicyDenied(planted.call(toolName, {}), `tool_name ${toolName} with a read-only fixture entry of the same name`);
  }
  const withEntries = planted.bash(BASH_DELETE);
  const withoutEntries = plainBaseline.bash(BASH_DELETE);
  assertSilentAllow(withoutEntries, `Bash "${BASH_DELETE}" with no such entries (posture allow, resolved delete, no rule)`);
  assertSilentAllow(withEntries, `Bash "${BASH_DELETE}" with entries naming Bash and built-ins`);
  assert.deepEqual(classify(withEntries), classify(withoutEntries), "the planted built-in entries must not change the verdict of any call");
});

// --- H9 -----------------------------------------------------------------------------------------

test("AC-H9: tool_name missing or a non-string is denied (strict); locked AC-19 'missing' stays", () => {
  const sb = createGateSandbox();
  const missing = sb.run({ session_id: "s", hook_event_name: "PreToolUse", tool_input: { command: "true" } });
  assertPolicyDenied(missing, "tool_name missing entirely");
  for (const bad of [null, 123, true, {}, [], ""]) {
    assertPolicyDenied(sb.call(bad, { command: "true" }), `tool_name ${JSON.stringify(bad)}`);
  }
});

// --- H10 ----------------------------------------------------------------------------------------

test("AC-H10: Q-B, a kernel allow emits nothing: Bash kubectl get pod/x --context=c gives exit 0, empty stdout, empty stderr", () => {
  const sb = createGateSandbox();
  const run = sb.bash(BASH_GET);
  assert.equal(run.code, 0, `expected exit 0 for a clean read-only Bash call; got ${describeRun(run)}`);
  assert.equal(run.stdout, "", `Q-B: an allow must emit NOTHING on stdout (the gate is not an auto-approver); got ${describeRun(run)}`);
  assert.equal(run.stderr, "", `an allow must not write to stderr; got ${describeRun(run)}`);
});

// --- H11 / H11b ---------------------------------------------------------------------------------

test("AC-H11: forgery, path-scoped rule: posture deny plus an allow rule pairing the read-only marker with the mcp/docs/ prefix; Bash cannot forge the marker or the identity target; the genuine MCP call is not denied", () => {
  const sb = createGateSandbox();
  sb.setEntries([{ name: "docs", class: "read-only" }]);
  sb.writeProjectPolicy(
    policyOf({ defaultOutcome: "deny", rules: [{ id: "h11-allow-read-only-docs", effect: "allow", verbs: [MARKER_READ_ONLY], targets: ["mcp/docs/"] }] }),
  );
  assertSilentAllow(sb.mcp("docs", "x"), "genuine mcp__docs__x (control: the rule is reachable by the real record)");
  assertPolicyDenied(sb.bash("echo x > mcp/docs/x"), "Bash redirect forging the identity target");
  assertPolicyDenied(sb.bash(`kubectl ${MARKER_READ_ONLY} pods/x --context=c`), "Bash forging the marker as a verb token");
});

test("AC-H11b: forgery, CLASS-ONLY rule (PT-14a): posture deny plus an allow rule on the read-only marker with NO targets; a Bash verb token equal to the marker is denied; the genuine MCP call is not denied", () => {
  const sb = createGateSandbox();
  sb.setEntries([{ name: "docs", class: "read-only" }]);
  sb.writeProjectPolicy(policyOf({ defaultOutcome: "deny", rules: [{ id: "h11b-allow-read-only-class", effect: "allow", verbs: [MARKER_READ_ONLY] }] }));
  assertSilentAllow(sb.mcp("docs", "x"), "genuine mcp__docs__x (control: the class-wide rule is reachable by the real record)");
  assertPolicyDenied(sb.bash(`rm ${MARKER_READ_ONLY} a/b --context=c`), "Bash rm with the marker as a token");
  assertPolicyDenied(sb.bash(`kubectl ${MARKER_READ_ONLY} pods/x --context=c`), "Bash kubectl with the marker as the verb token");
});

// --- H12 ----------------------------------------------------------------------------------------

test("AC-H12: the gate is env-immune: with CLAUDE_PROJECT_DIR pointing at a second tree holding a different fixture, the verdict follows the sandbox's own fixture (both directions)", () => {
  const rule = policyOf({ rules: [{ id: "h12-deny-remote-mutating-docs", effect: "deny", verbs: [MARKER_REMOTE_MUTATING], targets: ["mcp/docs/"], rationale: "H12-CLASS-RULE-DENY" }] });

  // direction A: the sandbox says remote-mutating (denied by the rule); the decoy says read-only
  const a = createGateSandbox();
  a.setEntries([{ name: "docs", class: "remote-mutating" }]);
  a.writeProjectPolicy(rule);
  const decoyReadOnly = makeDecoyProjectTree([{ name: "docs", class: "read-only" }]);
  const runA = a.mcp("docs", "x", { CLAUDE_PROJECT_DIR: decoyReadOnly });
  assertPolicyDenied(runA, "sandbox fixture says remote-mutating while CLAUDE_PROJECT_DIR holds a read-only decoy");
  assert.equal(denyReason(runA), "H12-CLASS-RULE-DENY", "the deny must come from the rule applied to the SANDBOX fixture's class");

  // direction B: the sandbox says read-only (not denied); the decoy says remote-mutating
  const b = createGateSandbox();
  b.setEntries([{ name: "docs", class: "read-only" }]);
  b.writeProjectPolicy(rule);
  const decoyRemote = makeDecoyProjectTree([{ name: "docs", class: "remote-mutating" }]);
  assertSilentAllow(b.mcp("docs", "x", { CLAUDE_PROJECT_DIR: decoyRemote }), "sandbox fixture says read-only while CLAUDE_PROJECT_DIR holds a remote-mutating decoy");
});

// --- H13 ----------------------------------------------------------------------------------------

/** Names the hook imports from the gate module (export names are not defined by the plan; derived
 * from the hook's own import statement at run time). */
function gateImportNames(hookSource: string): string[] | undefined {
  const match = /import\s*\{([^}]*)\}\s*from\s*["']\.\.\/src\/policy\/gate\/decide-tool-call\.ts["']/.exec(hookSource);
  if (match === null) return undefined;
  const names = (match[1] ?? "")
    .split(",")
    .map((part) => (part.trim().split(/\s+as\s+/)[0] ?? "").trim())
    .filter((n) => n.length > 0);
  return names.length > 0 ? names : undefined;
}

/** A pass-through wrapper around the REAL gate module (renamed to *.real.ts) that, per H13_MODE,
 * replaces the real result with an odd shape. Shape-agnostic: it mutates whatever the real gate
 * returned. It records what it did in H13_MARK so the test can prove the mutation was applied. */
function wrapperSource(names: string[]): string {
  const exportsBlock = names
    .map((n) => `export const ${n} = typeof real.${n} === "function" ? wrap(real.${n}) : real.${n};`)
    .join("\n");
  return `import * as real from "./decide-tool-call.real.ts";
import fs from "node:fs";
const MODE = process.env.H13_MODE ?? "control";
const MARK = process.env.H13_MARK;
function isThenable(x) { return x !== null && (typeof x === "object" || typeof x === "function") && typeof x.then === "function"; }
function walk(x, fn) {
  if (Array.isArray(x)) return x.map((v) => walk(v, fn));
  if (x !== null && typeof x === "object") { const o = {}; for (const [k, v] of Object.entries(x)) { const r = fn(k, v); if (r !== DROP) o[k] = walk(r === KEEP ? v : r, fn); } return o; }
  return x;
}
const DROP = Symbol("drop");
const KEEP = Symbol("keep");
function mutate(res) {
  let out = res;
  let applied = true;
  if (MODE === "ask") {
    let n = 0;
    const swap = (x) => { if (x === "allow") { n++; return "ask"; } if (Array.isArray(x)) return x.map(swap); if (x !== null && typeof x === "object") { const o = {}; for (const [k, v] of Object.entries(x)) o[k] = swap(v); return o; } return x; };
    out = swap(res); applied = n > 0;
  } else if (MODE === "undefined") { out = undefined; }
  else if (MODE === "null") { out = null; }
  else if (MODE === "unknown-kind") { out = { kind: "h13-no-such-kind" }; }
  else if (MODE === "refusal-no-reason") {
    let n = 0;
    out = walk(res, (k) => { if (k === "reason") { n++; return DROP; } return KEEP; });
    applied = n > 0;
  }
  if (MARK) fs.writeFileSync(MARK, JSON.stringify({ mode: MODE, applied, hadResult: res !== undefined && res !== null }));
  return out;
}
function wrap(fn) { return (...args) => { const res = fn(...args); return isThenable(res) ? res.then(mutate) : mutate(res); }; }
${exportsBlock}
`;
}

test("AC-H13: typed fail-closed output (PT-15): with the gate module returning each odd shape, the hook exits 2 or emits a deny JSON for every shape; silence only for an exact allow verdict", () => {
  const sb = createGateSandbox();
  const hookSource = fs.readFileSync(sb.hookPath, "utf8");
  const names = gateImportNames(hookSource);
  assert.ok(names !== undefined, "the hook must import its gate function(s) from src/policy/gate/decide-tool-call.ts (the plan's gate module); no such import found, so the gate is not built or not wired into the hook");
  const gateDir = path.join(sb.root, "src", "policy", "gate");
  const gateFile = path.join(gateDir, "decide-tool-call.ts");
  assert.ok(fs.existsSync(gateFile), `the sandbox copy must contain ${gateFile}`);
  fs.renameSync(gateFile, path.join(gateDir, "decide-tool-call.real.ts"));
  fs.writeFileSync(gateFile, wrapperSource(names), "utf8");

  const scenarios: { mode: string; tool: () => GateRun; expectBlocking: boolean }[] = [];
  const markFile = (mode: string): string => path.join(sb.root, `h13-mark-${mode}.json`);
  const runMode = (mode: string, toolName: string, toolInput: unknown): GateRun =>
    sb.call(toolName, toolInput, { H13_MODE: mode, H13_MARK: markFile(mode) });
  scenarios.push({ mode: "control", tool: () => runMode("control", "Bash", { command: BASH_GET }), expectBlocking: false });
  scenarios.push({ mode: "ask", tool: () => runMode("ask", "Bash", { command: BASH_GET }), expectBlocking: true });
  scenarios.push({ mode: "undefined", tool: () => runMode("undefined", "Bash", { command: BASH_GET }), expectBlocking: true });
  scenarios.push({ mode: "null", tool: () => runMode("null", "Bash", { command: BASH_GET }), expectBlocking: true });
  scenarios.push({ mode: "unknown-kind", tool: () => runMode("unknown-kind", "Bash", { command: BASH_GET }), expectBlocking: true });
  scenarios.push({ mode: "refusal-no-reason", tool: () => runMode("refusal-no-reason", "Write", {}), expectBlocking: true });

  for (const s of scenarios) {
    const run = s.tool();
    const mark = markFile(s.mode);
    assert.ok(fs.existsSync(mark), `H13 ${s.mode}: the hook never called the (wrapped) gate function, so the odd shape was never delivered; ${describeRun(run)}`);
    const record = JSON.parse(fs.readFileSync(mark, "utf8")) as { applied: boolean };
    assert.equal(record.applied, true, `H13 ${s.mode}: the odd shape could not be derived from the real gate result (the harness mutation did not apply); ${describeRun(run)}`);
    if (s.expectBlocking) {
      assert.ok(isBlocking(run), `H13 ${s.mode}: the hook must exit 2 (with stderr) or emit a deny JSON, never stay silent or allow; got ${describeRun(run)}`);
    } else {
      assertSilentAllow(run, `H13 ${s.mode} (pass-through control: an exact allow verdict is the ONLY silent outcome)`);
    }
  }
});
