// #308 story E0 (Issue #408), criteria 8 and 14: every shell fixture call in src/policy/fixtures/normalizer-calls.ts
// (the redirect, wrapper, quoting, multi-target and depth-cap shapes the S4 reviews locked) produces a record
// byte-identical to the one the UNMODIFIED tree produced before E0. The snapshot JSON was generated by running the
// normalizer on the tree at origin/master 6f78aee, in the RED commit, before any E0 code existed. A fixture added later
// is not in the snapshot, so the test names it and fails until it is triaged (regenerate on purpose, as a recorded act).
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { normalizeShellCall } from "./shell.ts";
import type { ShellCall } from "./shell.ts";
import * as fixtures from "../fixtures/normalizer-calls.ts";

const SNAPSHOT = JSON.parse(readFileSync(new URL("../fixtures/shell-fixture-records-pre-e0.json", import.meta.url), "utf8")) as Record<string, unknown>;

function shellFixtures(): Record<string, ShellCall> {
  const out: Record<string, ShellCall> = {};
  for (const [name, value] of Object.entries(fixtures)) {
    if (typeof value === "object" && value !== null && typeof (value as { command?: unknown }).command === "string") out[name] = value as ShellCall;
  }
  return out;
}

test("RO-redirect-fixtures-unchanged: every shell fixture record equals the pre-E0 snapshot, and the fixture name sets are equal", () => {
  const live = shellFixtures();
  assert.deepEqual(Object.keys(live).sort(), Object.keys(SNAPSHOT).sort(), "a fixture was added or removed since the snapshot");
  for (const [name, call] of Object.entries(live)) {
    assert.deepEqual(JSON.parse(JSON.stringify(normalizeShellCall(call))), SNAPSHOT[name], name);
  }
});

test("RO-redirect-fixtures-unchanged: the snapshot is not trivially small (at least 40 shell fixtures, several carrying a redirect)", () => {
  const names = Object.keys(SNAPSHOT);
  assert.ok(names.length >= 40, `only ${String(names.length)} fixtures`);
  assert.ok(Object.values(shellFixtures()).filter((c) => />/.test(c.command)).length >= 10);
});
